name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: yurihbm/homebrew-app-release/.github/workflows/release.yml@6de084a11acfd478185d11b60f2de0113e3f5c2e # v1.1.0
    permissions:
      contents: write
    with:
      project: Lucid.xcodeproj
      scheme: Lucid
      cask: lucid
