name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: xcode-27

    steps:
      - uses: yurihbm/homebrew-app-release/test@v0.1.0
        with:
          project: Lucid.xcodeproj
          scheme: Lucid
