name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: yurihbm/homebrew-app-release/.github/workflows/test.yml@aeecc50f0e87ca0d8f22203eacbe06afe221201c # v1.0.0
    with:
      project: Lucid.xcodeproj
      scheme: Lucid
